### ISSUE TITLE
Issue with style-src in Web.config

### ISSUE THREAD

**Issue by dwaxweiler** [NWebsec/NWebsec#125]
After updating to the latest version, I get the following exception when I visit the website:
```
The configuration element 'style-src' is not valid. The error is: Unable to cast object of type 'NWebsec.Modules.Configuration.Csp.CspDirectiveUnsafeInlineConfigurationElement' to type 'NWebsec.Modules.Configuration.Csp.CspDirectiveBaseConfigurationElement`1[NWebsec.Modules.Configuration.Csp.CspSourceConfigurationElement]'.
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Web.HttpContext.GetSection(String sectionName)
   at System.Web.Configuration.HttpConfigurationSystem.GetSection(String sectionName)
   at System.Web.Configuration.WebConfigurationManager.GetSection(String sectionName)
   at NWebsec.Helpers.ConfigHelper.GetConfig()
   at NWebsec.Helpers.CspUpgradeInsecureRequestHelper.get_Config()
   at NWebsec.Helpers.CspUpgradeInsecureRequestHelper.TryUpgradeInsecureRequest(HttpContextBase context)
   at NWebsec.Modules.HttpHeaderSecurityModule.AppBeginRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```
The line `<style-src self="true" unsafeInline="true" />` in my Web.config causes this issue. When I remove the `unsafeInline` attribute, it works fine. I use the ASP.NET 4 libs.

**Comment by klings** [comment]
Sounds unpleasant. I’ll have a look tonight.

**Comment by klings** [comment]
Thank you for reporting this! Version 5.1.1 will be available through NuGet in a few minutes and should solve the issue. Feel free to reopen the issue should you run into any similar problems.

**Comment by dwaxweiler** [comment]
You are welcome! Thank you for fixing this so quickly! It works now. :)
