### ISSUE TITLE
Bug in 5.1.0 release: The configuration element 'style-src' is not valid

### ISSUE THREAD

**Issue by i4rilu** [NWebsec/NWebsec#127]
When I try to allow unsafe inline style via

```
<style-src enabled="true" self="true" unsafeInline="true"/>
```

I get an exception:
```
System.Configuration.ConfigurationErrorsException: The configuration element 'style-src' is not valid. The error is: Unable to cast object of type 'NWebsec.Modules.Configuration.Csp.CspDirectiveUnsafeInlineConfigurationElement' to type 'NWebsec.Modules.Configuration.Csp.CspDirectiveBaseConfigurationElement`1[NWebsec.Modules.Configuration.Csp.CspSourceConfigurationElement]'. (.\web.config line xxx)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at NWebsec.Helpers.ConfigHelper.GetConfig()
   at NWebsec.Helpers.ConfigurationHeaderSetter.SetHstsHeader(IHttpContextWrapper httpContext, Boolean isHttps, Boolean upgradeSupported)
   at NWebsec.Helpers.ConfigurationHeaderSetter.SetSitewideHeadersFromConfig(HttpContextBase context)
   at NWebsec.Modules.HttpHeaderSecurityModule.AppBeginRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Options below work just fine:
```
<style-src enabled="true" self="true" unsafeInline="false"/>
<style-src enabled="true" self="true" />
```

Tech-stack: .NET 4.7; ASP.NET MVC 5.2.4

**Comment by klings** [comment]
Fixed in 5.1.1.
