### ISSUE TITLE
Server cannot append header after HTTP headers have been sent.

### ISSUE THREAD

**Issue by prainho** [NWebsec/NWebsec#93]
Hello,

I'm having this error:

System.Web.HttpException (0x80004005): Server cannot append header after HTTP headers have been sent.
   at System.Web.HttpHeaderCollection.SetHeader(String name, String value, Boolean replace)
   at System.Web.HttpHeaderCollection.Set(String name, String value)
   at NWebsec.Helpers.HeaderResultHandler.HandleHeaderResult(HttpResponseBase response, HeaderResult result)
   at NWebsec.Mvc.Helpers.HeaderOverrideHelper.SetXContentTypeOptionsHeader(HttpContextBase context)
   at NWebsec.Mvc.HttpHeaders.XContentTypeOptionsAttribute.SetHttpHeadersOnActionExecuted(ActionExecutedContext filterContext)
   at NWebsec.Mvc.HttpHeaders.Internals.HttpHeaderAttributeBase.OnActionExecuted(ActionExecutedContext filterContext)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

This XContentTypeOptionsAttribute if being added to my GlobalFilterCollection and is called in the global.asax Application_Start method.

**Comment by klings** [comment]
Which version of NWebsec are you using?

**Comment by prainho** [comment]
NWebsec - 4.3.0.0
NWebsec.Core - 1.6.0.0
NWebsec.Mvc - 4.3.0.0

**Comment by klings** [comment]
Weird, are you flushing the response manually?

**Comment by prainho** [comment]
No I'm not.

**Comment by klings** [comment]
This is not a common error when using NWebsec. Something is flushing your response early, ASP.NET does not do that by default. I'd need a simple repro in order to help out here.
